# Generated by Django 2.0.6 on 2021-06-06 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20210519_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todomodel',
            name='priority',
            field=models.CharField(choices=[('secondary', 'low'), ('info', 'normal'), ('danger', 'high')], max_length=50),
        ),
    ]
