# Generated by Django 2.0.6 on 2021-06-06 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20210606_1548'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuccesModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('memo', models.TextField()),
                ('priority', models.CharField(choices=[('secondary', 'low'), ('info', 'normal'), ('danger', 'high')], max_length=50)),
                ('duedate', models.DateField()),
            ],
        ),
    ]
