# Generated by Django 2.0.6 on 2021-06-06 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_succesmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SuccesModel',
            new_name='SuccessModel',
        ),
    ]
