# Generated by Django 2.0.6 on 2021-06-09 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_auto_20210606_1731'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SuccessModel',
        ),
        migrations.AddField(
            model_name='todomodel',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
